### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by csktan** [baidu-research/DeepBench#31]
Hi,
sorry it might be the basic things, although i am the beginner...
i am getting the error on include nccl.h no such file or directory and i am little confuse in **NCCl_PATH**
if some one could explain this issue
thank you so much.

**Comment by sharannarang** [comment]
`NCCL_PATH` points to NVIDIA's NCCL communication library. As mentioned in the README, NCCL library is available at https://github.com/NVIDIA/nccl. The benchmarks have been tested with commit b3a9e1333d9e2e1b8553b5843ba1ba4f7c79739d

Please setup the NCCL library and update the `NCCL_PATH` before compiling the `all_reduce` benchmark in DeepBench.

**Comment by csktan** [comment]
yea i checked it and it works thank you 
i have made a mistake to setup a path
👍
